[package]
name = "executor"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/substrate-move.git", subdir = "language/move-stdlib", rev = "main" }
deposit = { local = "..", addr_subst = { "std" = "0x1" } }

[addresses]
deposit = "0x1"
